---
- name: Provisioning App
  hosts: all
  become: true
#  vars:
#    db_host: 10.128.0.10
  tasks:
    - name: Update repositories cache and install "git, ruby full and required" package
#      ansible.builtin.apt:
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - git
        - ruby-full
        - ruby-bundler
        - build-essential
